apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis
  labels:
    app: my-redis
spec:
  selector:
    matchLabels:
      app: my-redis
  template:
    metadata:
      labels:
        app: my-redis  
    spec:
      containers:
      - image: redis
        name: my-redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service 
spec:
  selector:
    app: my-redis
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
