apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db 
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: admin
        - name:  POSTGRES_PASSWORD
          value: example
        - name: POSTGRES_DB
          value: test
        image: postgres
        name: db-projet
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
  - port: 5432  